"""Interface base classes — type markers only, no runtime enforcement."""


class DataSource: ...
class ProxyBuilderInterface: ...
class ODEEngineInterface: ...
class SingularDetectorInterface: ...
class BeliefBuilderInterface: ...
class AnomalyDetectorInterface: ...
class NarrativeDetectorInterface: ...
class ReflexivityDetectorInterface: ...
class SnapshotStoreInterface: ...
class PipelineInterface: ...
