#!/usr/bin/env python3
"""Build incentive review — credit score, demotion, anti-gaming, submission scoring.

Outputs:
    Output/system_learning/latest/incentive_review.json
    Output/system_learning/latest/incentive_review.md
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from _workspace_imports import add_scripts
add_scripts()
from _runtime_io import ROOT, ensure_dir

from _incentive_engine import build_incentive_review  # noqa: E402

OUTPUT_JSON = ROOT / "Output/system_learning/latest/incentive_review.json"
OUTPUT_MD = ROOT / "Output/system_learning/latest/incentive_review.md"


def _markdown(report: dict[str, Any]) -> str:
    credit = report["credit_score"]
    anti = report["anti_gaming"]
    lines = [
        "# Incentive Review",
        "",
        f"Generated: {report['generated_at']}",
        "",
        "## Credit Score",
        "",
        f"- Total score: {credit['total_score']}",
        f"- Active sources: {', '.join(credit['active_sources']) or 'none'}",
        f"- Promoted tier: {credit['promoted_tier']}",
        f"- Final tier: {credit['final_tier']}",
        f"- Demotion reasons: {', '.join(credit['demotion_reasons']) or 'none'}",
        "",
        "## Anti-Gaming",
        "",
        f"- Valid: {anti['valid']}",
        f"- Findings: {anti['finding_count']}",
        "",
    ]
    for item in anti.get("findings", [])[:10]:
        lines.append(f"- [{item['severity']}] {item['message']}")
    lines += ["", "## Submissions", ""]
    if not report["submissions"]:
        lines.append("- No submissions in registry.")
    else:
        for sub in report["submissions"]:
            lines.append(
                f"- `{sub['submission_id']}` priority={sub['effective_priority']} "
                f"credit_bonus={sub['credit_bonus']} gaps={sub['gaps'] or 'none'}"
            )
    lines += [
        "",
        "---",
        "",
        "Observation report only. Credit never grants authority.",
        "",
        "Generated by scripts/build_incentive_review.py",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Build incentive review report.")
    parser.add_argument("--json", action="store_true", help="Print JSON to stdout.")
    args = parser.parse_args()

    report = build_incentive_review(ROOT)
    ensure_dir(OUTPUT_JSON.parent)
    OUTPUT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    OUTPUT_MD.write_text(_markdown(report), encoding="utf-8")

    if args.json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
    else:
        print(f"Incentive review: {OUTPUT_MD.relative_to(ROOT)}")
        print(f"Credit score: {report['credit_score']['total_score']} -> {report['credit_score']['final_tier']}")


if __name__ == "__main__":
    main()
