from __future__ import annotations


DECISION_IMPACTS = (
    "BLOCK",
    "QUARANTINE",
    "DOWNWEIGHT",
    "PROMOTE",
    "ACTION_REQUIRED",
    "WARN_ONLY",
    "DISPLAY_ONLY",
    "NONE",
)
ACTIVE_DECISION_IMPACTS = {"BLOCK", "QUARANTINE", "DOWNWEIGHT", "PROMOTE"}
WEAK_ACTIVE_DECISION_IMPACTS = {"ACTION_REQUIRED"}
PASSIVE_DECISION_IMPACTS = {"WARN_ONLY", "DISPLAY_ONLY"}

ARTIFACT_STATUSES = ("ALIVE", "ALIVE_WEAK", "PASSIVE", "ZOMBIE", "DECORATIVE")
ARTIFACT_TYPES = ("AUDIT", "CONFIG", "LEDGER", "PROXY", "REPORT", "ROUTING_DECISION", "TRACE")
SEVERITIES = ("OK", "LOW", "MEDIUM", "HIGH", "CRITICAL")
