#!/usr/bin/env bash
# Bootstrap a fresh checkout of system-workspace into a runnable layout.
#
# After cloning system-workspace, run this script from the repo root:
#
#   ./scripts/bootstrap.sh
#
# It will:
#   1. Clone the 4 sister repos into the locations the workspace expects
#   2. Recreate the 4 top-level symlinks that point into Workbench/
#   3. Print next steps for venv installation
#
# Re-running is safe: existing repos are pulled, existing symlinks are kept.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GH_USER="xubo15384751795-sys"
GH_PROTO="${GH_PROTO:-ssh}"  # set GH_PROTO=https to use HTTPS instead

repo_url() {
  local name="$1"
  if [ "$GH_PROTO" = "https" ]; then
    echo "https://github.com/${GH_USER}/${name}.git"
  else
    echo "git@github.com:${GH_USER}/${name}.git"
  fi
}

clone_or_update() {
  local repo_name="$1"
  local target_path="$2"
  local url
  url="$(repo_url "$repo_name")"

  if [ -d "$target_path/.git" ]; then
    echo "[update] $target_path"
    git -C "$target_path" pull --ff-only
  else
    echo "[clone]  $url -> $target_path"
    mkdir -p "$(dirname "$target_path")"
    git clone "$url" "$target_path"
  fi
}

ensure_symlink() {
  local link_path="$1"
  local target="$2"

  if [ -L "$link_path" ]; then
    return 0
  fi
  if [ -e "$link_path" ]; then
    echo "[skip]   $link_path exists and is not a symlink (leaving alone)"
    return 0
  fi
  echo "[link]   $link_path -> $target"
  ln -s "$target" "$link_path"
}

echo "=== Cloning sister repositories ==="
clone_or_update "Structural-Deformation-Research-System" "Structural Deformation Research System"
clone_or_update "structural-workbench"                    "Workbench"
clone_or_update "structural-risk-harvester"               "Workbench/data_providers/structural-risk-harvester"
clone_or_update "system-learning-hub"                     "Workbench/governance/system-learning-hub"

echo
echo "=== Recreating top-level symlinks ==="
ensure_symlink "Structural Research Harness" "Workbench/agent_harness/structural-research-harness"
ensure_symlink "System Learning Hub"         "Workbench/governance/system-learning-hub"
ensure_symlink "Structural Risk Harvester"   "Workbench/data_providers/structural-risk-harvester"
ensure_symlink "contracts"                   "Workbench/contracts"

cat <<'EOF'

=== Bootstrap complete ===

Next steps (venvs are deliberately not created automatically):

  # Workbench (NLP / ML / contracts)
  python3 -m venv Workbench/.venv
  source Workbench/.venv/bin/activate
  pip install -e "Workbench[dev]"
  deactivate

  # Structural Deformation Research System
  python3 -m venv "Structural Deformation Research System/.venv"
  source "Structural Deformation Research System/.venv/bin/activate"
  pip install -e "Structural Deformation Research System"
  deactivate

  # Structural Risk Harvester
  python3 -m venv Workbench/data_providers/structural-risk-harvester/.venv
  source Workbench/data_providers/structural-risk-harvester/.venv/bin/activate
  pip install -e Workbench/data_providers/structural-risk-harvester
  deactivate

  # System Learning Hub
  python3 -m venv Workbench/governance/system-learning-hub/.venv
  source Workbench/governance/system-learning-hub/.venv/bin/activate
  pip install -e Workbench/governance/system-learning-hub
  deactivate

Data directories (Data/, Output/) are intentionally not committed. They are
regenerated by harvester / deformation runs as needed.

EOF
