#!/usr/bin/env bash
# Bootstrap a fresh checkout of system-workspace into a runnable layout.
#
# After cloning system-workspace, run this script from the repo root:
#
#   git clone git@github.com:USER/system-workspace.git System
#   cd System
#   ./scripts/bootstrap.sh
#
# It will:
#   1. Verify packages/ layout exists (monorepo — no submodules)
#   2. Recreate top-level compatibility symlinks
#   3. Link packages/learning_hub/data -> workspace Data/system_learning
#   4. Print next steps for venv installation
#
# Re-running is safe: existing symlinks are kept.
#
# Git policy: governance/git_workspace_policy.md

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ensure_symlink() {
  local link_path="$1"
  local target="$2"

  if [ -L "$link_path" ]; then
    return 0
  fi
  if [ -e "$link_path" ]; then
    echo "[WARN]  $link_path exists and is not a symlink — workspace may be inconsistent"
    return 1
  fi
  echo "[link]   $link_path -> $target"
  ln -s "$target" "$link_path"
}

echo "=== Verifying packages/ layout (monorepo) ==="
for pkg in workbench framework harvester learning_hub; do
  if [ ! -d "$ROOT/packages/$pkg" ]; then
    echo "[ERROR] packages/$pkg not found — repository may be incomplete"
    exit 1
  fi
done
echo "[ok]     packages/{workbench,framework,harvester,learning_hub} present"

echo
echo "=== Recreating top-level symlinks ==="
ensure_symlink "Structural Research Harness" "packages/workbench/agents/harness" || true
ensure_symlink "System Learning Hub"         "packages/learning_hub" || true
ensure_symlink "Structural Risk Harvester"   "packages/harvester" || true
ensure_symlink "contracts"                   "packages/workbench/contracts" || true

echo
echo "=== Linking Learning Hub data alias ==="
HUB_DATA="$ROOT/packages/learning_hub/data"
HUB_DATA_TARGET="../../Data/system_learning"
if [ -L "$HUB_DATA" ]; then
  : # already linked
elif [ -d "$HUB_DATA" ] && [ -z "$(ls -A "$HUB_DATA" 2>/dev/null)" ]; then
  rmdir "$HUB_DATA" || true
  ensure_symlink "packages/learning_hub/data" "$HUB_DATA_TARGET" || true
elif [ ! -e "$HUB_DATA" ]; then
  ensure_symlink "packages/learning_hub/data" "$HUB_DATA_TARGET" || true
else
  echo "[skip]   packages/learning_hub/data exists with content (migrate to Data/system_learning/ manually)"
fi

cat <<'EOF'

=== Bootstrap complete ===

Next steps (venvs are deliberately not created automatically):

  # Workbench (NLP / ML / contracts)
  python3 -m venv packages/workbench/.venv
  source packages/workbench/.venv/bin/activate
  pip install -e "packages/workbench[dev]"
  deactivate

  # deformation-framework
  python3 -m venv "packages/framework/.venv"
  source "packages/framework/.venv/bin/activate"
  pip install -e "packages/framework"
  deactivate

  # Structural Risk Harvester
  python3 -m venv packages/harvester/.venv
  source packages/harvester/.venv/bin/activate
  pip install -e packages/harvester
  deactivate

  # System Learning Hub
  python3 -m venv packages/learning_hub/.venv
  source packages/learning_hub/.venv/bin/activate
  pip install -e packages/learning_hub
  deactivate

Data directories (Data/, Output/) are intentionally not committed. They are
regenerated by harvester / deformation runs as needed.

Layout map: governance/repo_layout_map.md
Git policy: governance/git_workspace_policy.md

Optional automation (recommended on macOS):

  bash scripts/orchestrate.sh install-automation

This installs:
  - daily System pipeline (launchd, default 07:00)
  - Horizon daily run (launchd, default 06:30)
  - Paper post-commit sync hook
  - Paper fswatch debounced sync (requires: brew install fswatch)

Manual orchestration:

  bash scripts/orchestrate.sh daily
  bash scripts/orchestrate.sh horizon
  bash scripts/orchestrate.sh paper-sync

EOF
