#!/usr/bin/env bash
# Bootstrap a fresh checkout of system-workspace into a runnable layout.
#
# After cloning system-workspace, run this script from the repo root:
#
#   git clone --recurse-submodules git@github.com:USER/system-workspace.git System
#   cd System
#   ./scripts/bootstrap.sh
#
# Or without --recurse-submodules:
#
#   git clone git@github.com:USER/system-workspace.git System
#   cd System
#   ./scripts/bootstrap.sh
#
# It will:
#   1. Init/update git submodules (four sister repos at workspace root)
#   2. Recreate top-level compatibility symlinks
#   3. Link system-learning-hub/data -> workspace Data/system_learning
#   4. Print next steps for venv installation
#
# Re-running is safe: submodules are synced, existing symlinks are kept.
#
# Git policy: governance/git_workspace_policy.md

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GH_USER="xubo15384751795-sys"
GH_PROTO="${GH_PROTO:-ssh}"  # set GH_PROTO=https to use HTTPS instead

repo_url() {
  local name="$1"
  if [ "$GH_PROTO" = "https" ]; then
    echo "https://github.com/${GH_USER}/${name}.git"
  else
    echo "git@github.com:${GH_USER}/${name}.git"
  fi
}

clone_or_update() {
  local repo_name="$1"
  local target_path="$2"
  local url
  url="$(repo_url "$repo_name")"

  if [ -d "$target_path/.git" ]; then
    echo "[update] $target_path"
    git -C "$target_path" pull --ff-only
  else
    echo "[clone]  $url -> $target_path"
    mkdir -p "$(dirname "$target_path")"
    git clone "$url" "$target_path"
  fi
}

ensure_symlink() {
  local link_path="$1"
  local target="$2"

  if [ -L "$link_path" ]; then
    return 0
  fi
  if [ -e "$link_path" ]; then
    echo "[skip]   $link_path exists and is not a symlink (leaving alone)"
    return 0
  fi
  echo "[link]   $link_path -> $target"
  ln -s "$target" "$link_path"
}

echo "=== Initializing sister repositories (git submodules) ==="
if [ -f "$ROOT/.gitmodules" ]; then
  git submodule sync --recursive
  git submodule update --init --recursive
else
  echo "[warn]   .gitmodules not found — falling back to direct clone (legacy checkout)"
  clone_or_update "Structural-Deformation-Research-System" "Structural Deformation Research System"
  clone_or_update "structural-workbench"                    "Workbench"
  clone_or_update "structural-risk-harvester"               "structural-risk-harvester"
  clone_or_update "system-learning-hub"                     "system-learning-hub"
fi

echo
echo "=== Recreating top-level symlinks ==="
ensure_symlink "Structural Research Harness" "Workbench/agents/harness"
ensure_symlink "System Learning Hub"         "system-learning-hub"
ensure_symlink "Structural Risk Harvester"   "structural-risk-harvester"
ensure_symlink "contracts"                   "Workbench/contracts"

echo
echo "=== Linking Learning Hub data alias ==="
HUB_DATA="$ROOT/system-learning-hub/data"
HUB_DATA_TARGET="../Data/system_learning"
if [ -L "$HUB_DATA" ]; then
  : # already linked
elif [ -d "$HUB_DATA" ] && [ -z "$(ls -A "$HUB_DATA" 2>/dev/null)" ]; then
  rmdir "$HUB_DATA"
  ensure_symlink "system-learning-hub/data" "$HUB_DATA_TARGET"
elif [ ! -e "$HUB_DATA" ]; then
  ensure_symlink "system-learning-hub/data" "$HUB_DATA_TARGET"
else
  echo "[skip]   system-learning-hub/data exists with content (migrate to Data/system_learning/ manually)"
fi

cat <<'EOF'

=== Bootstrap complete ===

Next steps (venvs are deliberately not created automatically):

  # Workbench (NLP / ML / contracts)
  python3 -m venv Workbench/.venv
  source Workbench/.venv/bin/activate
  pip install -e "Workbench[dev]"
  deactivate

  # Structural Deformation Research System
  python3 -m venv "Structural Deformation Research System/.venv"
  source "Structural Deformation Research System/.venv/bin/activate"
  pip install -e "Structural Deformation Research System"
  deactivate

  # Structural Risk Harvester
  python3 -m venv structural-risk-harvester/.venv
  source structural-risk-harvester/.venv/bin/activate
  pip install -e structural-risk-harvester
  deactivate

  # System Learning Hub
  python3 -m venv system-learning-hub/.venv
  source system-learning-hub/.venv/bin/activate
  pip install -e system-learning-hub
  deactivate

Data directories (Data/, Output/) are intentionally not committed. They are
regenerated by harvester / deformation runs as needed.

Layout map: governance/repo_layout_map.md
Git policy: governance/git_workspace_policy.md

EOF
